resolver: https://raw.githubusercontent.com/input-output-hk/cardano-haskell/578c5777b8f4db1f8f5d4d8c07b1945dc0cbaab7/snapshots/cardano-1.25.1.yaml
compiler: ghc-8.6.5

allow-newer: true

packages:
  - explorer-api
  - rest-common

extra-deps:
  - esqueleto-3.2.0
  - persistent-2.10.5.1
  - persistent-postgresql-2.10.1.2
  - persistent-template-2.8.2.3
  - Diff-0.4.0

  - git: https://github.com/input-output-hk/cardano-db-sync
    commit: 1c7dbdac93e4d75118f1592dbb411f4f6a617128
    # Author: Erik de Castro Lopo <erikd@mega-nerd.com>
    # Date:   Wed Jan 27 08:22:21 2021 +1100
    #
    #     Version 8.0.0
    subdirs:
    - cardano-db

ghc-options:
  $locals: -ddump-to-file -ddump-hi
  cardano-explorer-api: -Wall -Werror -fwarn-redundant-constraints

nix:
  shell-file: nix/stack-shell.nix

flags:
  # Bundle VRF crypto in libsodium and do not rely on an external fork to have it.
  # This still requires the host system to have the 'standard' libsodium installed.
  cardano-crypto-praos:
    external-libsodium-vrf: false
