steps:
  - label: 'check-cabal-project'
    command: 'nix-build ./nix -A iohkNix.checkCabalProject -o check-cabal-project.sh && ./check-cabal-project.sh'
    agents:
      system: x86_64-linux

  - label: 'Docker Images'
    command:
      - "nix-build .buildkite/docker-build-push.nix -o docker-build-push"
      - "./docker-build-push"
    branches: master
    agents:
      system: x86_64-linux
